CXX = g++
CXXFLAGS = -std=c++0x 

default: fantasyGame.cpp classFighter.cpp classFighter.h subclassGoblin.cpp subclassGoblin.h subclassBarbarian.cpp subclassBarbarian.h subclassBluemen.cpp subclassBluemen.h subclassMaryLittle.cpp subclassMaryLittle.h subclassReptile.cpp subclassReptile.h
	${CXX} ${CXXFLAGS} fantasyGame.cpp classFighter.cpp subclassGoblin.cpp subclassBarbarian.cpp subclassBluemen.cpp subclassMaryLittle.cpp subclassReptile.cpp -o fantasy